site_name: RDMA Programming Tutorial
site_description: A comprehensive guide to RDMA programming concepts and practices.
site_author: RDMA Experts
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.instant

nav:
  - Homepage: index.md
  - RDMA Basics:
      - Introduction to RDMA: 0_introduction.md
      - RDMA Verbs API: 1_rdma_verbs_api.md
      - Memory Registration: 2_memory_registration.md
      - Queue Pairs: 3_queue_pairs.md
  - GPUDirect RDMA: 4_gpudirect_rdma.md
  - Code Examples:
      - RDMA Write Example: code_examples/rdma_write.md
      - RDMA Read Example: code_examples/rdma_read.md
      - RDMA Write Example (GPU): code_examples/rdma_write_gpu.md
      - RDMA Read Example (GPU): code_examples/rdma_read_gpu.md
      - One-sided vs Two-sided Test: code_examples/one_sided_vs_two_sided.md
      - RC vs UD Test: code_examples/rc_vs_ud_.md
      - UCCL optimizations: code_examples/uccl_optimizations.md
      - AWS EFA: code_examples/aws_efa.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: !relative
  - pymdownx.superfences
extra_css:
  - extra.css      
  

